### ISSUE TITLE
Queuer by CocoaPod

### ISSUE THREAD

**Issue by nachoindenova** [FabrizioBrancati/Queuer#5] opened 2017-11-13 11:17 UTC
Hi Fabrizio,

I've imported your Queuer framework by CocoaPod (pod Queuer) in my own Framework that it's used in my app. When I try to do the Archive Xcode shows me this error:
_bitcode bundle could not be generated because '/MyFramework../Build/Products/Release-iphoneos/Queuer/Queuer.framework/Queuer' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/MyFramework.../Build/Products/Release-iphoneos/Queuer/Queuer.framework/Queuer' for architecture armv7._

I've tried several options searched by google but all have failed. I've downloaded the Queuer framework project and I've added to my framework and it works (without changing any parameters). 

Am I doing something wrong?
It's a shame I can't use it with CocoaPods.

Regards,

**Comment by FabrizioBrancati** [comment] 2017-11-20 22:28
Can you write here your `Podfile` please?

**Comment by FabrizioBrancati** [comment] 2017-11-27 23:33
I'm using `Queuer` in a couple of Apps with Bitcode enabled, so we need to investigate.
In the meantime, can you try this code inside your `Podfile`, please?

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

**Comment by nachoindenova** [comment] 2017-12-21 08:28
# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'MyLibrary' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyLibrary
  pod 'Queuer' 

  target 'MyLibraryTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

**Comment by FabrizioBrancati** [comment] 2017-12-25 23:18
I think that I found your issue.
How are you packaging your framework to be able to use it in your App?
Because I was able to reproduce your bug by copying the framework created with the project (Build or Archive), into the App, instead of using CocoaPods or Carthage.
By using CocoaPods or Carthage to create the framework, I was able to archive to App with bitcode

**Comment by FabrizioBrancati** [comment] 2018-02-18 20:58
Can I close this issue?
Is your problem been resolved?

**Comment by FabrizioBrancati** [comment] 2018-03-24 16:10
I will close this issue since there was no activity. 
Feel free to reopen it if it was not resolved 👍

**Closed by FabrizioBrancati** 2018-03-24 16:10 UTC
